Владелец ИТ компании утверждает, что каждый будний день обслуживает одинаковое количество клиентов. Чтобы проверить эту гипотезу, исследователь записывает количество клиентов, которые обращаются в службу поддержки, и обнаруживает следующее:

Понедельник: 40 клиентов
вторник: 50 клиентов
Среда: 47 клиентов
Четверг: 53 клиентов
Пятница: 60 клиента
Используйте следующие шаги, чтобы выполнить тест на соответствие хи-квадрат в Python, чтобы определить, согласуются ли данные с мнением владельца ИТ компании.

expected = [50,50,50,50,50]
